#include <iostream>


//HOW TO UPLOAD PROJECT TO GITHUB
//IT WILL ASK YOU TO LOG INTO GITHUB BEFORE SHARING ON YOUR FIRST REPOSITORY SHARE
//ONCE YOU MAKE A CHANGE AND WANT TO REUPLOAD (COMMIT AND PUSH), DO THE FOLLOWING
int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
